spring.application.name=project-service
server.port=8083

#Jwt__secrets
jwt.secret=ZhtdFOEhJ7ImA6RxqAgs9GbOx4h7zxmb4KC75bTvPDE=
jwt.expiration=900000

#DB connections
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=postgres
spring.datasource.password=1805

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true